WITH DURATION_INFO AS (
    SELECT
        H.HISTORY_ID,
        C.DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT
    D.HISTORY_ID,
    FLOOR(D.DAILY_FEE * D.DIFF * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM DURATION_INFO D LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON D.DURATION_TYPE = P.DURATION_TYPE
    AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;
