SELECT FLAVOR
FROM (
    -- 상반기 데이터와 7월 데이터를 먼저 합치기
    SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
    UNION ALL
    SELECT FLAVOR, TOTAL_ORDER FROM JULY
) AS COMBINED_DATA
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;