SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A JOIN PATIENT P ON A.PT_NO = P.PT_NO
    JOIN DOCTOR D ON A.MDDR_ID = DR_ID
WHERE A.MCDP_CD = 'CS' AND A.APNT_YMD LIKE '2022-04-13%' AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD;