WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_TABLE WHERE HOUR < 23
)

SELECT T.HOUR, COUNT(O.ANIMAL_ID) AS COUNT
FROM TIME_TABLE T LEFT JOIN ANIMAL_OUTS O ON T.HOUR = HOUR(O.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR;