SELECT CONCAT('/home/grep/src/', CONCAT(BOARD_ID, CONCAT('/', CONCAT(FILE_ID, CONCAT(FILE_NAME, FILE_EXT))))) AS FILE_PATH
FROM USED_GOODS_BOARD NATURAL JOIN USED_GOODS_FILE
WHERE VIEWS = (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
ORDER BY FILE_ID DESC;